[versions]
kotlin = "2.4.0"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.11.0"
hikari = "7.0.2"
slf4j = "2.0.18"
logback = "1.5.13"
mysql-connector = "9.7.0"
postgresql = "42.7.11"
luajava = "4.1.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mysql-connector = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
luajava = { module = "party.iroiro.luajava:luajava", version.ref = "luajava" }
luajit = { module = "party.iroiro.luajava:luajit", version.ref = "luajava" }
lua51 = { module = "party.iroiro.luajava:lua51", version.ref = "luajava" }
lua52 = { module = "party.iroiro.luajava:lua52", version.ref = "luajava" }
lua53 = { module = "party.iroiro.luajava:lua53", version.ref = "luajava" }
lua54 = { module = "party.iroiro.luajava:lua54", version.ref = "luajava" }
lua55 = { module = "party.iroiro.luajava:lua55", version.ref = "luajava" }

[bundles]

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
