package com.kxxnzstdsw.dialect

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.slf4j.LoggerFactory
import java.sql.Connection

/**
 * DuckDB 方言 —— 嵌入式列式 OLAP 数据库。
 *
 * ## 连接约定
 *
 * `host` / `port` 完全忽略，仅由 `database` 字段承载 DuckDB URL 核心部分：
 *
 * | database 取值 | DuckDB JDBC URL | 用途 |
 * | --- | --- | --- |
 * | `""` 或 `":memory:"` | `jdbc:duckdb:` | 嵌入式内存模式（每连接私有 DB） |
 * | `"/path/data.duckdb"` | `jdbc:duckdb:/path/data.duckdb` | 本地 DuckDB 文件（多进程共享，文件锁） |
 * | `"/path/data.csv"` | `jdbc:duckdb:/path/data.csv` | 直查 CSV 文件 |
 * | `"/path/data.parquet"` | `jdbc:duckdb:/path/data.parquet` | 直查 Parquet 文件 |
 * | `"/path/data.json"` | `jdbc:duckdb:/path/data.json` | 直查 JSON 文件 |
 * | `"/path/data.xlsx"` | 预转换临时 .duckdb | POI 读取 Excel → 临时 DuckDB 文件 |
 *
 * ## 方言特性
 *
 * - 默认 schema 名是 `main`（DuckDB 命名约定）
 * - 标识符使用双引号包裹（标准 SQL）
 * - 自增主键用 `GENERATED BY DEFAULT AS IDENTITY`
 * - DDL 重建走原生 `SHOW CREATE TABLE name`（≥0.10）
 * - 不支持 `ON UPDATE CASCADE`：检测到时强制改写为 `NO ACTION`
 * - 嵌入式无用户/权限/触发器概念，对应方法抛 `UnsupportedOperationException`
 * - 存储过程不支持；函数仅支持 `MACRO` / 标量 `FUNCTION`
 */
class DuckDBDialect : DatabaseDialect {
    private val logger = LoggerFactory.getLogger(DuckDBDialect::class.java)

    override val driverName = "Duckdb"
    override val jdbcDriverClassName = "org.duckdb.DuckDBDriver"

    // v2.8: 前端连接表单元数据
    override val displayName = "DuckDB (Embedded OLAP)"
    override val connectionType = ConnectionType.EMBEDDED
    override val requiresHost = false
    override val requiresPort = false
    override val supportsUser = false
    override val supportsPassword = false
    override val supportsSchema = true
    override val supportsCrossDatabase = true      // ATTACH 多文件
    override val jdbcUrlExample = "jdbc:duckdb:/path/to/data.duckdb  (or :memory: / .csv / .parquet / .json / .xlsx)"
    override val capabilities = setOf(
        DialectCapability.ROUTINES,
        DialectCapability.VIEWS,
        DialectCapability.INDEXES,
        DialectCapability.FOREIGN_KEYS,
        DialectCapability.MULTI_SCHEMA,
        DialectCapability.EXPORT,
        DialectCapability.EMBEDDED_MODE,
    )

    override fun buildJdbcUrl(host: String, port: Int, database: String): String {
        // host/port 完全忽略；database 承载 DuckDB URL 主体
        val resolved = if (database.isBlank()) "" else resolveLocalFile(database)
        return "jdbc:duckdb:$resolved"
    }

    /**
     * 处理 Excel → 临时 DuckDB 文件；其他文件直通。
     */
    private fun resolveLocalFile(database: String): String {
        return if (ExcelToDuckDbCache.isExcelFile(database)) {
            ExcelToDuckDbCache.getOrCreate(database)
        } else {
            database
        }
    }

    override fun configureConnectionForStreaming(conn: Connection): Boolean {
        // DuckDB 流式读取无需关闭 autoCommit（PG 才需要）
        return conn.autoCommit
    }

    override fun setSearchPath(conn: Connection, schema: String) {
        if (schema.isBlank()) return
        conn.createStatement().use { stmt ->
            stmt.execute("SET schema = ${quoteIdentifier(schema)}")
        }
    }

    override fun buildSetSearchPathSql(schema: String): String? {
        if (schema.isBlank()) return null
        return "SET schema = ${quoteIdentifier(schema)}"
    }

    override fun quoteIdentifier(identifier: String): String {
        // DuckDB 使用双引号包裹（v2.9 #16 转 DialectUtil.quoteWith）
        return DialectUtil.quoteWith(identifier, '"')
    }

    // region Schema / Database 导航

    override suspend fun listDatabases(conn: Connection): List<String> = withContext(Dispatchers.IO) {
        // DuckDB 的"数据库"概念：通过 ATTACH 关联的 .duckdb 文件 + 内置 system/temp
        // 这里查询 duckdb_databases() 拿到已 attach 的库名
        val databases = mutableSetOf<String>()
        try {
            conn.createStatement().use { stmt ->
                stmt.executeQuery(
                    "SELECT database_name FROM duckdb_databases() " +
                    "WHERE database_name NOT IN ('system', 'temp') " +
                    "ORDER BY database_name"
                ).use { rs ->
                    while (rs.next()) {
                        val name = rs.getString(1) ?: continue
                        if (name.isNotBlank()) databases.add(name)
                    }
                }
            }
        } catch (e: Exception) {
            logger.debug("duckdb_databases() 查询失败: ${e.message}")
        }
        // DuckDB 的默认 schema 名 "main" 同时被业务层当作默认数据库引用 —— 一并返回
        databases.add("main")
        databases.toList().sorted()
    }

    override suspend fun listSchemas(conn: Connection, database: String): List<String> = withContext(Dispatchers.IO) {
        val schemas = mutableListOf<String>()
        conn.createStatement().use { stmt ->
            stmt.executeQuery(
                "SELECT schema_name FROM information_schema.schemata " +
                "WHERE schema_name NOT IN ('information_schema', 'pg_catalog') " +
                "ORDER BY schema_name"
            ).use { rs ->
                while (rs.next()) schemas.add(rs.getString(1) ?: continue)
            }
        }
        if (schemas.isEmpty()) schemas.add("main")
        schemas
    }

    override suspend fun createSchema(conn: Connection, name: String, options: Map<String, String>, ifNotExists: Boolean): Boolean = withContext(Dispatchers.IO) {
        val safeName = sanitizeIdentifier(name, "schema name")
        val ifClause = if (ifNotExists) "IF NOT EXISTS " else ""
        conn.createStatement().use { stmt ->
            stmt.execute("CREATE SCHEMA ${ifClause}${quoteIdentifier(safeName)}")
        }
        true
    }

    override suspend fun deleteSchema(conn: Connection, name: String, ifExists: Boolean): Boolean = withContext(Dispatchers.IO) {
        val safeName = sanitizeIdentifier(name, "schema name")
        val ifClause = if (ifExists) "IF EXISTS " else ""
        conn.createStatement().use { stmt ->
            stmt.execute("DROP SCHEMA ${ifClause}${quoteIdentifier(safeName)}")
        }
        true
    }

    // endregion

    // region Table / Column

    override suspend fun listTables(conn: Connection, database: String, schema: String): List<Map<String, String>> = withContext(Dispatchers.IO) {
        val tables = mutableListOf<Map<String, String>>()
        val targetSchema = schema.ifBlank { "main" }
        val query = """
            SELECT table_name, table_type
            FROM information_schema.tables
            WHERE table_schema = ?
            ORDER BY table_name
        """.trimIndent()
        conn.prepareStatement(query).use { stmt ->
            stmt.setString(1, targetSchema)
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    tables.add(mapOf(
                        "name" to (rs.getString("table_name") ?: ""),
                        "type" to (rs.getString("table_type") ?: "BASE TABLE")
                    ))
                }
            }
        }
        tables
    }

    /**
     * DuckDB listColumns：使用 information_schema.columns + key_column_usage。
     * 注：duckdb_constraints() 没有 column_name 列（只有 constraint_column_names LIST），
     *     因此主键解析直接走 information_schema.key_column_usage。
     */
    override suspend fun listColumns(
        conn: Connection,
        database: String,
        schema: String,
        tableName: String
    ): List<Map<String, Any?>> = withContext(Dispatchers.IO) {
        val targetSchema = schema.ifBlank { "main" }
        val columns = mutableListOf<Map<String, Any?>>()

        // 1. 主键列表 —— information_schema.key_column_usage 是 DuckDB 1.x 稳定路径
        val primaryKeys = mutableSetOf<String>()
        conn.prepareStatement(
            "SELECT kcu.column_name FROM information_schema.key_column_usage kcu " +
            "JOIN information_schema.table_constraints tc " +
            "  ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema " +
            "WHERE tc.constraint_type = 'PRIMARY KEY' " +
            "  AND kcu.table_name = ? AND kcu.table_schema = ?"
        ).use { stmt ->
            stmt.setString(1, tableName)
            stmt.setString(2, targetSchema)
            stmt.executeQuery().use { rs ->
                while (rs.next()) primaryKeys.add(rs.getString(1) ?: continue)
            }
        }

        // 2. 列定义
        conn.prepareStatement(
            "SELECT column_name, data_type, is_nullable, column_default " +
            "FROM information_schema.columns " +
            "WHERE table_name = ? AND table_schema = ? " +
            "ORDER BY ordinal_position"
        ).use { stmt ->
            stmt.setString(1, tableName)
            stmt.setString(2, targetSchema)
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    val name = rs.getString("column_name") ?: continue
                    val dataType = rs.getString("data_type") ?: ""
                    val nullable = rs.getString("is_nullable")
                    val defaultVal = rs.getString("column_default")
                    columns.add(mapOf(
                        "name" to name,
                        "type" to dataType,
                        "size" to extractSize(dataType),
                        "nullable" to ("YES".equals(nullable, ignoreCase = true)),
                        "isPrimaryKey" to (name in primaryKeys),
                        "defaultValue" to defaultVal
                    ))
                }
            }
        }
        columns
    }

    /**
     * 从 DuckDB 类型字符串提取 size —— 例如 VARCHAR(255) → 255, DECIMAL(10,2) → 10
     */
    private fun extractSize(dataType: String): Int {
        val match = Regex("""\(\s*(\d+)""").find(dataType) ?: return 0
        return match.groupValues[1].toIntOrNull() ?: 0
    }

    override suspend fun createUser(conn: Connection, user: String, password: String, host: String): Boolean {
        throw UnsupportedOperationException("Duckdb 不支持用户管理")
    }

    override suspend fun deleteUser(conn: Connection, user: String, host: String): Boolean {
        throw UnsupportedOperationException("Duckdb 不支持用户管理")
    }

    override suspend fun updatePassword(conn: Connection, user: String, password: String, host: String): Boolean {
        throw UnsupportedOperationException("Duckdb 不支持用户管理")
    }

    override suspend fun listUsers(conn: Connection): List<Map<String, String>> {
        throw UnsupportedOperationException("Duckdb 不支持用户列表")
    }

    override suspend fun updatePrivileges(
        conn: Connection,
        user: String,
        schema: String,
        privileges: List<String>,
        isGrant: Boolean,
        tableName: String?,
        withGrantOption: Boolean
    ): Boolean {
        throw UnsupportedOperationException("Duckdb 不支持权限管理")
    }

    override suspend fun listPrivileges(conn: Connection, user: String, host: String): List<Map<String, String>> {
        throw UnsupportedOperationException("Duckdb 不支持权限查询")
    }

    override suspend fun listAllGrants(conn: Connection, user: String, host: String): List<Map<String, String>> {
        throw UnsupportedOperationException("Duckdb 不支持权限查询")
    }

    // endregion

    // region DDL 构建

    override fun buildColumnDefinition(
        name: String,
        type: String,
        size: Int?,
        nullable: Boolean,
        isPrimaryKey: Boolean,
        defaultValue: String?,
        autoIncrement: Boolean
    ): String = buildString {
        append(quoteIdentifier(name))
        append(" ")
        when {
            // 自增主键：DuckDB 1.5.5 不支持 GENERATED BY DEFAULT AS IDENTITY 与表级 PK 组合
            // （报 "Constraint not implemented"），也不支持 INTEGER PRIMARY KEY 的 ROWID 自动填充。
            // 唯一可行：DuckDB 显式 CREATE SEQUENCE + 列 DEFAULT nextval(...) + 表级 PRIMARY KEY。
            autoIncrement && isPrimaryKey -> {
                append(buildTypeSpec(type, size))
                append(" DEFAULT nextval('")
                append(autoIncrementSequenceName(name))
                append("')")
            }
            // 非主键的自增：使用 IDENTITY 语法
            autoIncrement -> {
                append(buildTypeSpec(type, size))
                append(" GENERATED BY DEFAULT AS IDENTITY")
            }
            else -> append(buildTypeSpec(type, size))
        }
        if (!autoIncrement && !nullable) append(" NOT NULL")
        if (defaultValue != null && !autoIncrement) {
            append(" DEFAULT ")
            append(if (UNQUOTED_DEFAULT_REGEX.matches(defaultValue)) {
                defaultValue
            } else {
                "'${defaultValue.replace("'", "''")}'"
            })
        }
    }

    /** DuckDB 自增主键列绑定的 SEQUENCE 命名约定：seq_<colname>。 */
    private fun autoIncrementSequenceName(columnName: String): String = "seq_$columnName"

    /**
     * DuckDB 自增主键需要在 CREATE TABLE 之前先 CREATE SEQUENCE —— DEFAULT nextval 必须能找到序列。
     * 通过 buildPreCreateStatements 钩子实现（v2.7 SPI 扩展）。
     */
    override fun buildPreCreateStatements(tableName: String, autoIncrementColumns: List<String>): List<String> =
        autoIncrementColumns.map { col ->
            "CREATE SEQUENCE IF NOT EXISTS ${autoIncrementSequenceName(col)} START 1"
        }

    override fun buildAddColumnSQL(tableName: String, columnDef: String): String {
        return "ALTER TABLE ${quoteIdentifier(tableName)} ADD COLUMN $columnDef"
    }

    override fun buildDropColumnSQL(tableName: String, columnName: String): String {
        return "ALTER TABLE ${quoteIdentifier(tableName)} DROP COLUMN ${quoteIdentifier(columnName)}"
    }

    /**
     * DuckDB 支持单条 ALTER TABLE ... ALTER COLUMN ... SET TYPE 等子句，
     * 一次只能改一个属性（type / rename / set default / drop default / set not null / drop not null）。
     */
    override fun buildModifyColumnSQL(
        tableName: String,
        name: String,
        type: String?,
        size: Int?,
        nullable: Boolean,
        defaultValue: String?,
        newName: String?
    ): String {
        val table = quoteIdentifier(tableName)
        val col = quoteIdentifier(name)
        return when {
            !type.isNullOrBlank() -> {
                val typeSpec = buildTypeSpec(type, size)
                "ALTER TABLE $table ALTER COLUMN $col SET DATA TYPE $typeSpec"
            }
            newName != null -> "ALTER TABLE $table RENAME COLUMN $col TO ${quoteIdentifier(newName)}"
            defaultValue != null -> {
                val literal = if (UNQUOTED_DEFAULT_REGEX.matches(defaultValue)) {
                    defaultValue
                } else {
                    "'${defaultValue.replace("'", "''")}'"
                }
                "ALTER TABLE $table ALTER COLUMN $col SET DEFAULT $literal"
            }
            !nullable -> "ALTER TABLE $table ALTER COLUMN $col SET NOT NULL"
            nullable -> "ALTER TABLE $table ALTER COLUMN $col DROP NOT NULL"
            else -> throw IllegalArgumentException("MODIFY_COLUMN 调用缺少任何修改属性")
        }
    }

    /**
     * DuckDB 1.5.x 不支持 `SHOW CREATE TABLE`。从 information_schema.columns + 约束信息手工重建。
     */
    override suspend fun getCreateTableDDL(conn: Connection, tableName: String): String = withContext(Dispatchers.IO) {
        val safeTable = sanitizeIdentifier(tableName, "table name")
        // 1. 列定义
        val colDefs = mutableListOf<String>()
        var tableExists = false
        conn.prepareStatement(
            "SELECT column_name, data_type, is_nullable, column_default " +
            "FROM information_schema.columns " +
            "WHERE table_name = ? ORDER BY ordinal_position"
        ).use { stmt ->
            stmt.setString(1, safeTable)
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    tableExists = true
                    val name = rs.getString("column_name") ?: continue
                    val type = rs.getString("data_type") ?: ""
                    val nullable = "YES".equals(rs.getString("is_nullable"), ignoreCase = true)
                    val def = rs.getString("column_default")
                    colDefs.add(buildColumnDefForDdl(name, type, nullable, def))
                }
            }
        }
        if (!tableExists) throw IllegalArgumentException("未找到表 '$safeTable'")

        // 2. 主键约束
        val pkCols = mutableListOf<String>()
        conn.prepareStatement(
            "SELECT kcu.column_name FROM information_schema.key_column_usage kcu " +
            "JOIN information_schema.table_constraints tc " +
            "  ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema " +
            "WHERE tc.constraint_type = 'PRIMARY KEY' AND kcu.table_name = ? " +
            "ORDER BY kcu.ordinal_position"
        ).use { stmt ->
            stmt.setString(1, safeTable)
            stmt.executeQuery().use { rs ->
                while (rs.next()) pkCols.add(rs.getString(1) ?: continue)
            }
        }
        if (pkCols.isNotEmpty()) {
            colDefs.add("PRIMARY KEY (${pkCols.joinToString(", ") { quoteIdentifier(it) }})")
        }

        // 3. UNIQUE 约束
        conn.prepareStatement(
            "SELECT kcu.column_name, kcu.constraint_name FROM information_schema.key_column_usage kcu " +
            "JOIN information_schema.table_constraints tc " +
            "  ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema " +
            "WHERE tc.constraint_type = 'UNIQUE' AND kcu.table_name = ? " +
            "ORDER BY kcu.constraint_name, kcu.ordinal_position"
        ).use { stmt ->
            stmt.setString(1, safeTable)
            val grouped = mutableMapOf<String, MutableList<String>>()
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    val col = rs.getString(1) ?: continue
                    val cn = rs.getString(2) ?: continue
                    grouped.getOrPut(cn) { mutableListOf() }.add(col)
                }
            }
            for ((cn, cols) in grouped) {
                colDefs.add("CONSTRAINT ${quoteIdentifier(cn)} UNIQUE (${cols.joinToString(", ") { quoteIdentifier(it) }})")
            }
        }

        // 4. 外键约束
        val fkText = mutableListOf<String>()
        conn.prepareStatement(
            "SELECT constraint_name, constraint_text FROM duckdb_constraints() " +
            "WHERE table_name = ? AND constraint_type = 'FOREIGN KEY'"
        ).use { stmt ->
            stmt.setString(1, safeTable)
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    val cn = rs.getString("constraint_name") ?: continue
                    val text = rs.getString("constraint_text") ?: continue
                    fkText.add("CONSTRAINT ${quoteIdentifier(cn)} $text")
                }
            }
        }
        colDefs.addAll(fkText)

        return@withContext "CREATE TABLE ${quoteIdentifier(safeTable)} (\n  " +
            colDefs.joinToString(",\n  ") + "\n)"
    }

    /**
     * 从 information_schema 反推列定义 DDL 片段。
     */
    private fun buildColumnDefForDdl(
        name: String,
        dataType: String,
        nullable: Boolean,
        defaultExpr: String?
    ): String {
        val sb = StringBuilder()
        sb.append(quoteIdentifier(name)).append(' ').append(dataType)
        if (!nullable) sb.append(" NOT NULL")
        if (!defaultExpr.isNullOrBlank()) sb.append(" DEFAULT ").append(defaultExpr)
        return sb.toString()
    }

    override fun buildTableOptionsSQL(options: Map<String, String>): String = "" // DuckDB 无表级选项

    override fun buildPostCreateStatements(tableName: String, options: Map<String, String>): List<String> {
        // DuckDB 支持 COMMENT ON TABLE
        val statements = mutableListOf<String>()
        val comment = options["comment"]
        if (!comment.isNullOrBlank()) {
            val escaped = comment.replace("'", "''")
            statements.add("COMMENT ON TABLE ${quoteIdentifier(tableName)} IS '$escaped'")
        }
        return statements
    }

    // endregion

    // region SQL 安全校验

    override fun validateSqlFragment(sql: String, label: String) {
        DialectUtil.validateSqlFragment(sql, label, DANGEROUS_KEYWORD_REGEXES)
    }

    override fun validateOrderBy(sql: String) {
        DialectUtil.validateOrderBy(sql, ORDER_BY_REGEX)
    }

    // endregion

    // region 函数 / 宏管理（无存储过程，仅 MACRO / 标量 FUNCTION）

    override suspend fun listRoutines(conn: Connection, schema: String): List<Map<String, String>> = withContext(Dispatchers.IO) {
        val targetSchema = schema.ifBlank { "main" }
        val routines = mutableListOf<Map<String, String>>()
        try {
            conn.prepareStatement(
                "SELECT function_name, function_type, parameters, description, return_type " +
                "FROM duckdb_functions() " +
                "WHERE schema_name = ? AND function_type IN ('macro', 'scalar') " +
                "ORDER BY function_name"
            ).use { stmt ->
                stmt.setString(1, targetSchema)
                stmt.executeQuery().use { rs ->
                    while (rs.next()) {
                        val name = rs.getString("function_name") ?: continue
                        val type = rs.getString("function_type") ?: "macro"
                        val routineType = if (type.equals("scalar", ignoreCase = true)) "FUNCTION" else "MACRO"
                        val params = rs.getString("parameters") ?: ""
                        val desc = rs.getString("description") ?: ""
                        val ret = rs.getString("return_type") ?: ""
                        val argCount = params.split(",").count { it.isNotBlank() }.toString()
                        routines.add(mapOf(
                            "name" to name,
                            "routine_type" to routineType,
                            "return_type" to ret,
                            "language" to "sql",
                            "security_definer" to "SECURITY INVOKER",
                            "volatility" to "VOLATILE",
                            "arg_count" to argCount,
                            "arg_names" to params,
                            "schema" to targetSchema,
                            "description" to desc,
                            "trigger_table" to ""
                        ))
                    }
                }
            }
        } catch (e: Exception) {
            logger.debug("duckdb_functions() 不可用，回退到空列表: ${e.message}")
        }
        routines
    }

    override suspend fun getRoutineDDL(conn: Connection, routineName: String, schema: String): String = withContext(Dispatchers.IO) {
        val safeName = sanitizeIdentifier(routineName, "routine name")
        try {
            // DuckDB 1.x：duckdb_functions() 中 MACRO 的定义字段是 macro_definition（非 definition / description）
            // 同时通过 schema_name + function_name 精确定位，避免与同名 built-in 函数混淆
            conn.prepareStatement(
                "SELECT macro_definition, parameters FROM duckdb_functions() " +
                "WHERE function_name = ? AND function_type = 'macro'"
            ).use { stmt ->
                stmt.setString(1, safeName)
                stmt.executeQuery().use { rs ->
                    while (rs.next()) {
                        val def = rs.getString("macro_definition")
                        if (!def.isNullOrBlank()) {
                            return@withContext "CREATE OR REPLACE MACRO ${quoteIdentifier(safeName)}${rs.getString("parameters")} AS $def"
                        }
                    }
                }
            }
        } catch (e: Exception) {
            logger.debug("查询 MACRO DDL 失败: ${e.message}")
        }
        throw IllegalArgumentException("未找到函数/宏 '$safeName'")
    }

    override suspend fun createRoutine(conn: Connection, ddl: String): Boolean = withContext(Dispatchers.IO) {
        // DuckDB 接受 CREATE MACRO / CREATE OR REPLACE MACRO / CREATE FUNCTION 等
        conn.createStatement().use { stmt -> stmt.execute(ddl) }
        true
    }

    override suspend fun dropRoutine(
        conn: Connection,
        routineName: String,
        routineType: String,
        schema: String,
        ifExists: Boolean,
        cascade: Boolean
    ): Boolean = withContext(Dispatchers.IO) {
        val safeName = sanitizeIdentifier(routineName, "routine name")
        val ifClause = if (ifExists) "IF EXISTS " else ""
        val sql = when (routineType.uppercase()) {
            "FUNCTION", "MACRO" -> "DROP MACRO $ifClause${quoteIdentifier(safeName)}"
            "PROCEDURE" -> throw UnsupportedOperationException("Duckdb 不支持存储过程")
            else -> throw IllegalArgumentException("不支持的 routine 类型: $routineType")
        }
        conn.createStatement().use { stmt -> stmt.execute(sql) }
        true
    }

    override suspend fun callRoutine(
        conn: Connection,
        routineName: String,
        routineType: String,
        schema: String,
        args: List<String?>
    ): Map<String, Any?> = withContext(Dispatchers.IO) {
        val safeName = sanitizeIdentifier(routineName, "routine name")
        val placeholders = args.joinToString(", ") { "?" }
        // DuckDB 没有 PROCEDURE；MACRO / FUNCTION 都通过 SELECT 模拟
        if (routineType.equals("PROCEDURE", ignoreCase = true)) {
            throw UnsupportedOperationException("Duckdb 不支持存储过程调用")
        }
        val sql = "SELECT ${quoteIdentifier(safeName)}($placeholders) AS result"
        conn.prepareStatement(sql).use { stmt ->
            for ((i, v) in args.withIndex()) {
                if (v == null) stmt.setNull(i + 1, java.sql.Types.NULL)
                else stmt.setString(i + 1, v)
            }
            stmt.executeQuery().use { rs ->
                if (rs.next()) {
                    return@withContext mapOf(
                        "result" to rs.getObject(1),
                        "row_count" to 1,
                        "routine_type" to routineType.uppercase(),
                        "schema" to schema.ifBlank { "main" }
                    )
                }
            }
        }
        mapOf("result" to null, "row_count" to 0, "routine_type" to routineType.uppercase(), "schema" to schema.ifBlank { "main" })
    }

    override suspend fun getRoutineInfo(conn: Connection, routineName: String, schema: String): Map<String, String> = withContext(Dispatchers.IO) {
        val targetSchema = schema.ifBlank { "main" }
        val safeName = sanitizeIdentifier(routineName, "routine name")
        try {
            conn.prepareStatement(
                "SELECT function_name, function_type, parameters, description, return_type " +
                "FROM duckdb_functions() WHERE schema_name = ? AND function_name = ?"
            ).use { stmt ->
                stmt.setString(1, targetSchema)
                stmt.setString(2, safeName)
                stmt.executeQuery().use { rs ->
                    if (rs.next()) {
                        val type = rs.getString("function_type") ?: "macro"
                        val routineType = if (type.equals("scalar", ignoreCase = true)) "FUNCTION" else "MACRO"
                        val params = rs.getString("parameters") ?: ""
                        val argCount = params.split(",").count { it.isNotBlank() }.toString()
                        return@withContext mapOf(
                            "name" to safeName,
                            "routine_type" to routineType,
                            "schema" to targetSchema,
                            "language" to "sql",
                            "return_type" to (rs.getString("return_type") ?: ""),
                            "volatility" to "VOLATILE",
                            "security_definer" to "SECURITY INVOKER",
                            "arg_count" to argCount,
                            "arg_names" to params,
                            "description" to (rs.getString("description") ?: ""),
                            "trigger_table" to ""
                        )
                    }
                }
            }
        } catch (_: Exception) {}
        throw IllegalArgumentException("未找到函数/宏 '$safeName'")
    }

    override suspend fun debugRoutine(conn: Connection, routineName: String, schema: String): List<Map<String, String>> = withContext(Dispatchers.IO) {
        val targetSchema = schema.ifBlank { "main" }
        val safeName = sanitizeIdentifier(routineName, "routine name")
        val results = mutableListOf<Map<String, String>>()
        // INFO
        try {
            val info = getRoutineInfo(conn, safeName, targetSchema)
            results.add(mapOf(
                "type" to "INFO",
                "output" to buildString {
                    appendLine("Name: ${info["name"]}")
                    appendLine("Schema: ${info["schema"]}")
                    appendLine("Type: ${info["routine_type"]}")
                    appendLine("Language: ${info["language"]}")
                    appendLine("Return: ${info["return_type"]}")
                }
            ))
        } catch (e: Exception) {
            results.add(mapOf("type" to "INFO", "output" to "(not found: ${e.message})"))
        }
        // DDL
        try {
            val ddl = getRoutineDDL(conn, safeName, targetSchema)
            results.add(mapOf("type" to "DDL", "output" to ddl))
        } catch (e: Exception) {
            results.add(mapOf("type" to "DDL", "output" to "(no DDL: ${e.message})"))
        }
        results
    }

    /**
     * DuckDB 不支持存储过程，ROUTINE DDL 仅做轻量语法校验。
     */
    override suspend fun validateRoutineDDL(conn: Connection, ddl: String): Boolean = withContext(Dispatchers.IO) {
        val trimmed = ddl.trim().trimEnd(';')
        if (trimmed.contains(';')) throw IllegalArgumentException("DDL 不允许包含多条语句（分号）")
        // 拒绝 PG 风格 $$ ... $$ 块（PG 函数体在 DuckDB 中会执行但不解析）
        if (trimmed.contains("""$$""")) {
            throw IllegalArgumentException("Duckdb 不支持 PostgreSQL 风格 '$$ ... $$' 函数体，请使用 DuckDB MACRO 语法")
        }
        val normalized = trimmed.replace(Regex("""[`"]"""), "")
        val match = Regex("""(?i)CREATE\s+(?:OR\s+REPLACE\s+)?(MACRO|FUNCTION|PROCEDURE)\s+(\w+)(?:\.(\w+))?""").find(normalized)
            ?: throw IllegalArgumentException("无法从 DDL 中解析对象类型/名称")
        val objType = match.groupValues[1].uppercase()
        if (objType == "PROCEDURE") throw UnsupportedOperationException("Duckdb 不支持存储过程 (PROCEDURE)")
        true
    }

    // endregion

    // region Views

    override suspend fun listViews(conn: Connection, schema: String): List<Map<String, String>> = withContext(Dispatchers.IO) {
        val targetSchema = schema.ifBlank { "main" }
        val views = mutableListOf<Map<String, String>>()
        conn.prepareStatement(
            "SELECT table_name FROM information_schema.views WHERE table_schema = ? ORDER BY table_name"
        ).use { stmt ->
            stmt.setString(1, targetSchema)
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    views.add(mapOf(
                        "name" to (rs.getString(1) ?: ""),
                        "type" to "VIEW",
                        "definition" to ""
                    ))
                }
            }
        }
        views
    }

    override suspend fun createView(conn: Connection, viewName: String, definition: String): Boolean = withContext(Dispatchers.IO) {
        val safeName = sanitizeIdentifier(viewName, "view name")
        if (definition.contains(';')) throw IllegalArgumentException("视图定义不允许包含分号")
        conn.createStatement().use { stmt ->
            stmt.execute("CREATE VIEW ${quoteIdentifier(safeName)} AS $definition")
        }
        true
    }

    override suspend fun dropView(conn: Connection, viewName: String, ifExists: Boolean): Boolean = withContext(Dispatchers.IO) {
        val safeName = sanitizeIdentifier(viewName, "view name")
        val ifClause = if (ifExists) "IF EXISTS " else ""
        conn.createStatement().use { stmt ->
            stmt.execute("DROP VIEW ${ifClause}${quoteIdentifier(safeName)}")
        }
        true
    }

    /**
     * DuckDB 1.5.x 不支持 `SHOW CREATE VIEW`。从 information_schema.views.view_definition 重建。
     */
    override suspend fun getViewDDL(conn: Connection, viewName: String, schema: String): String = withContext(Dispatchers.IO) {
        val safeName = sanitizeIdentifier(viewName, "view name")
        conn.prepareStatement(
            "SELECT view_definition FROM information_schema.views WHERE table_name = ? LIMIT 1"
        ).use { stmt ->
            stmt.setString(1, safeName)
            stmt.executeQuery().use { rs ->
                if (rs.next()) {
                    val def = rs.getString("view_definition")
                        ?: throw IllegalArgumentException("视图 '$safeName' 无可用的定义")
                    return@withContext "CREATE VIEW ${quoteIdentifier(safeName)} AS $def"
                }
            }
        }
        throw IllegalArgumentException("未找到视图 '$safeName'")
    }

    // endregion

    // region Indexes

    override suspend fun listIndexes(conn: Connection, tableName: String): List<Map<String, String>> = withContext(Dispatchers.IO) {
        val safeTable = sanitizeIdentifier(tableName, "table name")
        val indexes = mutableListOf<Map<String, String>>()
        try {
            conn.prepareStatement(
                "SELECT index_name, sql, is_unique, is_primary " +
                "FROM duckdb_indexes() WHERE table_name = ? ORDER BY index_name"
            ).use { stmt ->
                stmt.setString(1, safeTable)
                stmt.executeQuery().use { rs ->
                    while (rs.next()) {
                        val name = rs.getString("index_name") ?: continue
                        val sql = rs.getString("sql") ?: ""
                        val isUnique = rs.getBoolean("is_unique")
                        val isPrimary = rs.getBoolean("is_primary")
                        // 解析列名 —— DuckDB 的 sql 形如 "CREATE INDEX [UNIQUE] INDEX name ON table (cols)"
                        val cols = extractIndexColumns(sql)
                        indexes.add(mapOf(
                            "name" to name,
                            "table" to safeTable,
                            "columns" to cols,
                            "unique" to isUnique.toString(),
                            "primary" to isPrimary.toString(),
                            "type" to "ART"
                        ))
                    }
                }
            }
        } catch (e: Exception) {
            logger.debug("duckdb_indexes() 查询失败: ${e.message}")
        }
        indexes
    }

    private fun extractIndexColumns(sql: String): String {
        // 例："CREATE INDEX idx_users_name ON main.users (name, age)"
        val match = Regex("""\(\s*([^)]+)\s*\)""").find(sql) ?: return ""
        return match.groupValues[1].split(",").joinToString(",") { it.trim() }
    }

    override suspend fun createIndex(
        conn: Connection,
        tableName: String,
        indexName: String,
        columns: List<String>,
        unique: Boolean,
        ifNotExists: Boolean
    ): Boolean = withContext(Dispatchers.IO) {
        val safeTable = sanitizeIdentifier(tableName, "table name")
        val safeIndex = sanitizeIdentifier(indexName, "index name")
        val safeCols = columns.joinToString(", ") { quoteIdentifier(it) }
        val sql = buildString {
            if (unique) append("CREATE UNIQUE INDEX ")
            else append("CREATE INDEX ")
            if (ifNotExists) append("IF NOT EXISTS ")
            append(quoteIdentifier(safeIndex))
            append(" ON ${quoteIdentifier(safeTable)} ($safeCols)")
        }
        conn.createStatement().use { stmt -> stmt.execute(sql) }
        true
    }

    override suspend fun dropIndex(conn: Connection, indexName: String, tableName: String?, ifExists: Boolean): Boolean = withContext(Dispatchers.IO) {
        val safeIndex = sanitizeIdentifier(indexName, "index name")
        val ifClause = if (ifExists) "IF EXISTS " else ""
        conn.createStatement().use { stmt ->
            stmt.execute("DROP INDEX ${ifClause}${quoteIdentifier(safeIndex)}")
        }
        true
    }

    // endregion

    // region Foreign Keys

    override suspend fun listForeignKeys(conn: Connection, tableName: String): List<Map<String, String>> = withContext(Dispatchers.IO) {
        val safeTable = sanitizeIdentifier(tableName, "table name")
        val fks = mutableListOf<Map<String, String>>()
        try {
            // DuckDB 提供 duckdb_constraints() 一次性返回所有约束信息
            conn.prepareStatement(
                "SELECT constraint_name, constraint_text, constraint_type " +
                "FROM duckdb_constraints() " +
                "WHERE table_name = ? AND constraint_type = 'FOREIGN KEY'"
            ).use { stmt ->
                stmt.setString(1, safeTable)
                stmt.executeQuery().use { rs ->
                    while (rs.next()) {
                        val name = rs.getString("constraint_name") ?: continue
                        val text = rs.getString("constraint_text") ?: ""
                        val parsed = parseForeignKeyText(text)
                        fks.add(mapOf(
                            "name" to name,
                            "table" to safeTable,
                            "columns" to parsed.columns.joinToString(","),
                            "ref_table" to parsed.refTable,
                            "ref_columns" to parsed.refColumns.joinToString(","),
                            "on_delete" to parsed.onDelete,
                            "on_update" to parsed.onUpdate
                        ))
                    }
                }
            }
        } catch (e: Exception) {
            logger.debug("duckdb_constraints() 查询失败: ${e.message}")
        }
        fks
    }

    /**
     * 解析 DuckDB 的 FK 约束文本，形如：
     * "FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION"
     */
    private data class ParsedFk(val columns: List<String>, val refTable: String, val refColumns: List<String>, val onDelete: String, val onUpdate: String)

    private fun parseForeignKeyText(text: String): ParsedFk {
        // columns
        val colMatch = Regex("""FOREIGN\s+KEY\s*\(([^)]+)\)""", RegexOption.IGNORE_CASE).find(text)
        val columns = colMatch?.groupValues?.get(1)?.split(",")?.map { it.trim() } ?: emptyList()
        // ref table + ref columns
        val refMatch = Regex("""REFERENCES\s+([^\s(]+)\s*\(([^)]+)\)""", RegexOption.IGNORE_CASE).find(text)
        val refTable = refMatch?.groupValues?.get(1)?.trim() ?: ""
        val refColumns = refMatch?.groupValues?.get(2)?.split(",")?.map { it.trim() } ?: emptyList()
        // on delete / on update
        val onDelete = Regex("""ON\s+DELETE\s+([A-Z_]+)""", RegexOption.IGNORE_CASE).find(text)?.groupValues?.get(1) ?: "NO ACTION"
        val onUpdate = Regex("""ON\s+UPDATE\s+([A-Z_]+)""", RegexOption.IGNORE_CASE).find(text)?.groupValues?.get(1) ?: "NO ACTION"
        return ParsedFk(columns, refTable, refColumns, onDelete.uppercase(), onUpdate.uppercase())
    }

    override suspend fun addForeignKey(
        conn: Connection,
        tableName: String,
        fkName: String,
        columns: List<String>,
        refTable: String,
        refColumns: List<String>,
        onDelete: String?,
        onUpdate: String?
    ): Boolean = withContext(Dispatchers.IO) {
        val safeTable = sanitizeIdentifier(tableName, "table name")
        val safeFk = sanitizeIdentifier(fkName, "foreign key name")
        val cols = columns.joinToString(", ") { quoteIdentifier(it) }
        val refCols = refColumns.joinToString(", ") { quoteIdentifier(it) }
        // DuckDB 不支持 ON UPDATE CASCADE —— 强制改写为 NO ACTION 并日志 warn
        val effectiveOnUpdate = if (onUpdate?.uppercase() == "CASCADE") {
            logger.warn("Duckdb 不支持 ON UPDATE CASCADE，已自动改写为 NO ACTION (FK=$safeFk)")
            "NO ACTION"
        } else {
            onUpdate
        }
        // DuckDB 同样不支持 ON DELETE CASCADE / SET NULL / SET DEFAULT —— 强制改写为 NO ACTION
        val effectiveOnDelete = if (onDelete?.uppercase() in setOf("CASCADE", "SET NULL", "SET DEFAULT")) {
            logger.warn("Duckdb 不支持 ON DELETE $onDelete，已自动改写为 NO ACTION (FK=$safeFk)")
            "NO ACTION"
        } else {
            onDelete
        }
        // DuckDB 不支持 ALTER TABLE ADD CONSTRAINT —— 通过"创建临时新表 → 复制数据 → 改名"的方式重建
        val fkInline = buildString {
            append("FOREIGN KEY ($cols) REFERENCES ${quoteIdentifier(refTable)} ($refCols)")
            effectiveOnDelete?.takeIf { it.isNotBlank() }?.let { append(" ON DELETE $it") }
            effectiveOnUpdate?.takeIf { it.isNotBlank() }?.let { append(" ON UPDATE $it") }
        }
        rebuildTableWithExtraConstraint(conn, safeTable, extraConstraintSql = "CONSTRAINT ${quoteIdentifier(safeFk)} $fkInline")
        true
    }

    override suspend fun dropForeignKey(conn: Connection, tableName: String, fkName: String, ifExists: Boolean): Boolean = withContext(Dispatchers.IO) {
        val safeTable = sanitizeIdentifier(tableName, "table name")
        val safeFk = sanitizeIdentifier(fkName, "foreign key name")
        // 1) 先按用户给出的名称精确查找
        var actualFkName = safeFk
        var exists = conn.prepareStatement(
            "SELECT constraint_name FROM duckdb_constraints() WHERE table_name = ? AND constraint_name = ? AND constraint_type = 'FOREIGN KEY' LIMIT 1"
        ).use { stmt ->
            stmt.setString(1, safeTable)
            stmt.setString(2, safeFk)
            stmt.executeQuery().use { rs -> if (rs.next()) rs.getString(1) else null }
        }
        // 2) DuckDB 1.x 会忽略 CREATE TABLE 中的 CONSTRAINT 子句名并自动生成 <table>_<cols>_fkey；
        //    此时若表上仅 1 个 FK，则把该 FK 视作目标（业务约定：业务层 drop FK 时若约束名失配即按唯一匹配兜底）
        if (exists == null) {
            val fkList = mutableListOf<String>()
            conn.prepareStatement(
                "SELECT constraint_name FROM duckdb_constraints() WHERE table_name = ? AND constraint_type = 'FOREIGN KEY' ORDER BY constraint_name"
            ).use { stmt ->
                stmt.setString(1, safeTable)
                stmt.executeQuery().use { rs -> while (rs.next()) rs.getString(1)?.let { fkList.add(it) } }
            }
            when {
                fkList.size == 1 -> {
                    actualFkName = fkList.first()
                    exists = actualFkName
                    logger.warn("Duckdb 忽略了用户给定的 FK 约束名 '$safeFk'，实际约束名为 '$actualFkName'，已按唯一匹配兜底删除")
                }
                fkList.isEmpty() -> {
                    if (!ifExists) throw IllegalArgumentException("外键 '$safeFk' 不存在")
                    return@withContext true
                }
                else -> throw IllegalArgumentException("外键 '$safeFk' 不存在且表上有多个 FK (${fkList.joinToString()})，无法确定目标")
            }
        }
        rebuildTableExcludingConstraint(conn, safeTable, constraintName = actualFkName)
        true
    }

    /**
     * 重建表，追加额外约束（用于 addForeignKey）。
     * 步骤：备份数据 → DROP → CREATE（同列定义 + extraConstraintSql）→ 数据回填
     */
    private fun rebuildTableWithExtraConstraint(
        conn: Connection,
        tableName: String,
        extraConstraintSql: String
    ) {
        // 1. 取出原表 DDL（去除外键约束后的精简版）
        val colDefs = mutableListOf<String>()
        conn.prepareStatement(
            "SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns " +
            "WHERE table_name = ? ORDER BY ordinal_position"
        ).use { stmt ->
            stmt.setString(1, tableName)
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    colDefs.add(buildColumnDefForDdl(
                        rs.getString("column_name") ?: continue,
                        rs.getString("data_type") ?: "",
                        "YES".equals(rs.getString("is_nullable"), ignoreCase = true),
                        rs.getString("column_default")
                    ))
                }
            }
        }
        // 2. 主键约束
        val pkCols = mutableListOf<String>()
        conn.prepareStatement(
            "SELECT kcu.column_name FROM information_schema.key_column_usage kcu " +
            "JOIN information_schema.table_constraints tc ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema " +
            "WHERE tc.constraint_type = 'PRIMARY KEY' AND kcu.table_name = ? ORDER BY kcu.ordinal_position"
        ).use { stmt ->
            stmt.setString(1, tableName)
            stmt.executeQuery().use { rs -> while (rs.next()) pkCols.add(rs.getString(1) ?: continue) }
        }
        if (pkCols.isNotEmpty()) colDefs.add("PRIMARY KEY (${pkCols.joinToString(", ") { quoteIdentifier(it) }})")
        colDefs.add(extraConstraintSql)

        val createDdl = "CREATE TABLE ${quoteIdentifier(tableName)} (\n  " +
            colDefs.joinToString(",\n  ") + "\n)"

        // 3. 备份 → DROP → CREATE → 数据回填
        val tempName = "${tableName}_tmp_${System.currentTimeMillis()}"
        conn.createStatement().use { stmt ->
            stmt.execute("CREATE TABLE ${quoteIdentifier(tempName)} AS SELECT * FROM ${quoteIdentifier(tableName)}")
            stmt.execute("DROP TABLE ${quoteIdentifier(tableName)}")
            stmt.execute(createDdl)
            stmt.execute("INSERT INTO ${quoteIdentifier(tableName)} SELECT * FROM ${quoteIdentifier(tempName)}")
            stmt.execute("DROP TABLE ${quoteIdentifier(tempName)}")
        }
    }

    /**
     * 重建表，排除指定外键约束（用于 dropForeignKey）。
     */
    private fun rebuildTableExcludingConstraint(
        conn: Connection,
        tableName: String,
        constraintName: String
    ) {
        val colDefs = mutableListOf<String>()
        conn.prepareStatement(
            "SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns " +
            "WHERE table_name = ? ORDER BY ordinal_position"
        ).use { stmt ->
            stmt.setString(1, tableName)
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    colDefs.add(buildColumnDefForDdl(
                        rs.getString("column_name") ?: continue,
                        rs.getString("data_type") ?: "",
                        "YES".equals(rs.getString("is_nullable"), ignoreCase = true),
                        rs.getString("column_default")
                    ))
                }
            }
        }
        // 主键
        val pkCols = mutableListOf<String>()
        conn.prepareStatement(
            "SELECT kcu.column_name FROM information_schema.key_column_usage kcu " +
            "JOIN information_schema.table_constraints tc ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema " +
            "WHERE tc.constraint_type = 'PRIMARY KEY' AND kcu.table_name = ? ORDER BY kcu.ordinal_position"
        ).use { stmt ->
            stmt.setString(1, tableName)
            stmt.executeQuery().use { rs -> while (rs.next()) pkCols.add(rs.getString(1) ?: continue) }
        }
        if (pkCols.isNotEmpty()) colDefs.add("PRIMARY KEY (${pkCols.joinToString(", ") { quoteIdentifier(it) }})")

        // 保留的 UNIQUE 约束（排除要删除的 FK）
        conn.prepareStatement(
            "SELECT kcu.column_name, kcu.constraint_name FROM information_schema.key_column_usage kcu " +
            "JOIN information_schema.table_constraints tc ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema " +
            "WHERE tc.constraint_type = 'UNIQUE' AND kcu.table_name = ? AND kcu.constraint_name != ? " +
            "ORDER BY kcu.constraint_name, kcu.ordinal_position"
        ).use { stmt ->
            stmt.setString(1, tableName)
            stmt.setString(2, constraintName)
            val grouped = mutableMapOf<String, MutableList<String>>()
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    val col = rs.getString(1) ?: continue
                    val cn = rs.getString(2) ?: continue
                    grouped.getOrPut(cn) { mutableListOf() }.add(col)
                }
            }
            for ((cn, cols) in grouped) {
                colDefs.add("CONSTRAINT ${quoteIdentifier(cn)} UNIQUE (${cols.joinToString(", ") { quoteIdentifier(it) }})")
            }
        }
        // 保留的其他 FK（排除要删除的）
        conn.prepareStatement(
            "SELECT constraint_name, constraint_text FROM duckdb_constraints() " +
            "WHERE table_name = ? AND constraint_type = 'FOREIGN KEY' AND constraint_name != ?"
        ).use { stmt ->
            stmt.setString(1, tableName)
            stmt.setString(2, constraintName)
            stmt.executeQuery().use { rs ->
                while (rs.next()) {
                    val cn = rs.getString("constraint_name") ?: continue
                    val text = rs.getString("constraint_text") ?: continue
                    colDefs.add("CONSTRAINT ${quoteIdentifier(cn)} $text")
                }
            }
        }

        val createDdl = "CREATE TABLE ${quoteIdentifier(tableName)} (\n  " +
            colDefs.joinToString(",\n  ") + "\n)"

        val tempName = "${tableName}_tmp_${System.currentTimeMillis()}"
        conn.createStatement().use { stmt ->
            stmt.execute("CREATE TABLE ${quoteIdentifier(tempName)} AS SELECT * FROM ${quoteIdentifier(tableName)}")
            stmt.execute("DROP TABLE ${quoteIdentifier(tableName)}")
            stmt.execute(createDdl)
            stmt.execute("INSERT INTO ${quoteIdentifier(tableName)} SELECT * FROM ${quoteIdentifier(tempName)}")
            stmt.execute("DROP TABLE ${quoteIdentifier(tempName)}")
        }
    }

    // endregion

    // region Triggers（不支持，沿用 SPI 默认抛异常）

    // listTriggers / getTriggerDDL 继承默认实现 → UnsupportedOperationException

    // endregion

    // region Table Operations

    override suspend fun renameTable(conn: Connection, oldName: String, newName: String): Boolean = withContext(Dispatchers.IO) {
        val safeOld = sanitizeIdentifier(oldName, "table name")
        val safeNew = sanitizeIdentifier(newName, "table name")
        conn.createStatement().use { stmt ->
            stmt.execute("ALTER TABLE ${quoteIdentifier(safeOld)} RENAME TO ${quoteIdentifier(safeNew)}")
        }
        true
    }

    override suspend fun truncateTable(conn: Connection, tableName: String): Boolean = withContext(Dispatchers.IO) {
        val safeTable = sanitizeIdentifier(tableName, "table name")
        conn.createStatement().use { stmt ->
            stmt.execute("TRUNCATE TABLE ${quoteIdentifier(safeTable)}")
        }
        true
    }

    // endregion

    // region SQL — EXPLAIN

    override suspend fun explainSQL(conn: Connection, sql: String): List<Map<String, String>> = withContext(Dispatchers.IO) {
        if (sql.contains(';')) throw IllegalArgumentException("EXPLAIN 不允许包含分号")
        val rows = mutableListOf<Map<String, String>>()
        conn.createStatement().use { stmt ->
            // 用 EXPLAIN 而非 EXPLAIN ANALYZE，避免真正执行副作用
            stmt.executeQuery("EXPLAIN $sql").use { rs ->
                val meta = rs.metaData
                val columnCount = meta.columnCount
                while (rs.next()) {
                    val row = mutableMapOf<String, String>()
                    for (i in 1..columnCount) {
                        row[meta.getColumnLabel(i)] = rs.getString(i) ?: ""
                    }
                    rows.add(row)
                }
            }
        }
        rows
    }

    // endregion

    // region Server

    override suspend fun getServerInfo(conn: Connection): Map<String, String> = withContext(Dispatchers.IO) {
        val meta = conn.metaData
        mapOf(
            "product" to (meta.databaseProductName ?: "DuckDB"),
            "version" to (meta.databaseProductVersion ?: ""),
            "driver" to (meta.driverName ?: ""),
            "driverVersion" to (meta.driverVersion ?: ""),
            "mode" to "embedded",
            "url" to (meta.url ?: "")
        )
    }

    // endregion

    // region 工具方法

    private fun sanitizeIdentifier(name: String, label: String): String {
        if (name.isBlank()) throw IllegalArgumentException("$label cannot be empty")
        if (name.contains(' ')) throw IllegalArgumentException("$label contains null byte")
        if (name.contains('\'')) throw IllegalArgumentException("$label contains single quote")
        if (name.contains('\\')) throw IllegalArgumentException("$label contains backslash")
        if (name.contains(';')) throw IllegalArgumentException("$label contains semicolon")
        return name
    }

    private fun buildTypeSpec(type: String, size: Int?): String {
        val upper = type.uppercase()
        return if (size != null && upper in SIZABLE_TYPES) {
            "$type($size)"
        } else {
            type
        }
    }

    companion object {
        /** ORDER BY 校验 —— DuckDB 支持双引号包裹（v2.9 #16 用 DialectUtil 工厂） */
        private val ORDER_BY_REGEX = DialectUtil.orderByRegex('"')

        /** DuckDB 危险关键词（v2.9 #16 用 DialectUtil 工厂） */
        private val DANGEROUS_KEYWORD_REGEXES: List<Regex> =
            DialectUtil.buildDangerousKeywordRegexes(setOf("MERGE", "INSTALL", "LOAD", "ATTACH", "DETACH", "COPY", "EXPORT"))

        /** DuckDB 可带 size 后缀的类型 */
        private val SIZABLE_TYPES = setOf("VARCHAR", "CHAR", "VARBINARY", "BINARY", "DECIMAL", "NUMERIC")

        /** 默认值中不需要加引号的字面量 */
        private val UNQUOTED_DEFAULT_REGEX = Regex(
            """\d+(\.\d+)?|NULL|CURRENT_TIMESTAMP|CURRENT_DATE|CURRENT_TIME|NOW\(\)|IDENTITY|TRUE|FALSE""",
            RegexOption.IGNORE_CASE
        )
    }

    // endregion
}